### ISSUE TITLE
Notification Bar on the bottom of screen will not be observed.

### ISSUE THREAD

**Issue by AH-dark** [cloudreve/ios-feedback#11]
![image](https://user-images.githubusercontent.com/51253685/170835416-809f46ab-7a5c-4a19-9376-a789b070efed.png)![image](https://user-images.githubusercontent.com/51253685/170835419-da985df7-e9eb-4d11-87c1-e66863bbe701.png)

Compare those screenshot, you can see that user can't see notice when they are writing on virtual keyboard.

This situation seems to have no feedback on the operating sensory, and brings a bad experience to users.

I think that the Notification Bar should be on top of the screen which may not be blocked by other components.

**Comment by AH-dark** [comment]
Maybe you can use another input method which will not autocomplete words. I'm sure this method exists on iOS.

**Comment by vvisionnn** [comment]
we have already have a plan to fix this
