### ISSUE TITLE
2FA 输入后按钮的功能

### ISSUE THREAD

**Issue by Candinya** [cloudreve/ios-feedback#16]
不知道这是不是我独有的习惯，在输入完 2FA 验证码之后我习惯性得按了这个又大又显眼的 Cancel 按钮…

![E8B6F540-78EC-4B9F-B204-E122C199F0F4](https://user-images.githubusercontent.com/20502130/208162426-82711b07-abe4-4f04-856e-93e8b7a5d5cf.jpeg)

不知道如果改成在 2FA 非空的时候是确认会不会更好？谢谢！ 🙏

**Comment by vvisionnn** [comment]
WOW, 这确实是一个很好的建议! 应该会在之后改成非空的时候确认或者确认和取消同时出现，请关注后续更新

> That's a great idea! probably this will be change to show confirm button when code is not empty or show cancel and confirm button at same time, please stay tuned for the future update.

**Comment by vvisionnn** [comment]
1.4.0-beta 已经更新了这个修改，详情请参考: [forum](https://forum.cloudreve.org/d/2745), 感谢反馈！
> this update is landed in 1.4.0-beta version, please check: [forum](https://forum.cloudreve.org/d/2745) Thanks for your feedback!
