### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by YUDONGLING** [cloudreve/ios-feedback#18]
1. Cloudreve后端重启后iOS端重新打开会退出登录跳转至输入站点链接的页面，是Bug还是设计时的考虑。
2. 输入站点链接后的输入账号密码页图标是否考虑也更换为站点自定义的图标。
谢谢。

**Comment by vvisionnn** [comment]
Hi @YUDONGLING 
1. 服务端重启之后，iOS 端需要重新登录是因为 session 过期，需要服务端自行保存 session (可以参考 web 端重启后是否需要重新登录)
2. 输入站点链接之后，图标会更换为站点图标，已经在计划中

> 1. iOS relogin after server side reboot just because of the session expire, session should be persisted by server side (frontend should relogin as well as you can see)
> 2. the logo will be change to custom site logo, and it is already in the roadmap

**Comment by YUDONGLING** [comment]
1. 但是比较奇怪的是同一个站点的账号A和B在iOS端登陆，其中A是当前使用的B是没在前台的(?好像不知道怎么描述)，在后端重启之后打开iOS端会直接跳转至输入站点链接的页面。重新登陆A之后，切换账户B不需要重新登陆，有点奇怪哈哈。另外建议一下有没有可能增加类似于记住账号密码，如果 session 过期则自动重新登陆。
2. 收到，辛苦啦。

**Comment by vvisionnn** [comment]
感谢反馈
如果是手动登录，默认会保存加密之后的账号密码在本机，如果 session 过期会尝试自动登录，
但是扫码绑定登录不支持，因为 Cloudreve 并不会保存用户原始密码（隐私考虑），后续可能会对 iOS 端使用其他的登录方式来彻底解决这个问题
> Thanks for the response
> if binding/login manually, iOS client will persist username/password on device but QRCode login is not supported yet because iOS client cannot get user's password (we respect user's privacy), may be this will be resolved cocmpletly by a custom login method in the future

**Comment by YUDONGLING** [comment]
1. 刚才又测试了一下，A使用密码登陆且当前使用，B使用扫码没在前台登陆。重启后端，继续返回输入站点地址页面应该是没有尝试重新登陆(?)，切换账号B提示登陆过期(这一点应该是符合设计预期的)。所以现在应该是“使用账号密码登陆”+“没在前台登陆的账号”才会触发后端重启 session 过期后的重新登陆，希望之后可以有所优化。
2. 刚才退出账号的时候又发现了一个有点奇怪的操作问题：账户管理页面无法删除当前登陆（正在使用、打了勾的账户），用户界面“退出登陆”会跳到输入站点地址页面，导致登陆了多个账户退出其中一个之后就无法直接切换其他账户。

**Comment by vvisionnn** [comment]
1. 自动尝试登录确实只在账户切换时使用，这个之后应该会改一改
2. 当前帐户不能删除是设计如此，因为在使用所以不能删除，不过可以之后把账户管理在退出登录之后也能使用加上
> 1. yes auto login will be use when switching user only, maybe we can refactor this for availability 
> 2. current account cannot be deleted is by design, because current this is in use, but probably we can make account managed after logout

**Comment by YUDONGLING** [comment]
Thanks
