### ISSUE TITLE
迎支持直接将文件或图片保存至ios的相册或文件

### ISSUE THREAD

**Issue by cmbrun** [cloudreve/ios-feedback#19]
如题。上传文件是很好用的。保存文件到iphone就很麻烦了，希望能优化一下。另外，软件最好能出ipad版，ipad是生产力工具，接受付费，谢谢！

**Comment by vvisionnn** [comment]
感谢建议！直接保存到相册之后应该可以加一个单独的选项，另外，iPadOS 版本在路上了～

**Comment by vvisionnn** [comment]
Hi 2.0.0 已经可以直接保存到相册，具体更新请参考 https://forum.cloudreve.org/d/3404
