### ISSUE TITLE
app crashes when your associated storage is 0KB

### ISSUE THREAD

**Issue by qaz1qazlol2** [cloudreve/ios-feedback#20]
当本用户组分配了0B的空间时点击程序内的用户时直接闪退

**Comment by qaz1qazlol2** [comment]
如果能修的话我直接开通连续包年

**Comment by vvisionnn** [comment]
Hello @qaz1qazlol2  

This will be fixed in the next version if I can repro this error, thanks for your feedback

> 这个将会在下个版本修复，如果我能复现这个问题的话，感谢反馈

**Comment by qaz1qazlol2** [comment]
> Hello @qaz1qazlol2
> 
> This will be fixed in the next version if I can repro this error, thanks for your feedback
> 
> > 这个将会在下个版本修复，如果我能复现这个问题的话，感谢反馈

pro.huang1111.cn You can try it,it has 0KB storage

**Comment by vvisionnn** [comment]
已经复现，感谢反馈，这个会在下个版本修复

> already reproduced, thanks for your feedback, this will be fixed in the next version

**Comment by vvisionnn** [comment]
fixed in version 2.1.0
