### ISSUE TITLE
ios客户端假死

### ISSUE THREAD

**Issue by rhymesgeckos0h** [cloudreve/ios-feedback#26]
操作系统：ipados 17.4.1
软件版本：cloudreve 3.0.2 （app store显示版本）
前置操作：将音频暂停后挂到后台
注意：无法稳定复现
视频：https://player.dogecloud.com/web/player.html?vcode=51ff3aa125cf3761&userId=2159&autoPlay=false
论坛链接：https://forum.cloudreve.org/d/4331

**ios客户端发现了很多假死、操作不顺手、离谱的操作（我是ipad，我不喜欢苹果手机）。我不知道在iphone上是什么样的情况，但是就ipad版本我是很不愿意在pro版本的基础上再付费400的。作为一个商业软件，cloudreve ios的表现实在不行。**

**Comment by vvisionnn** [comment]
since you say you met many error but I can only get one (which is this issue), how about report them all so I can fix them all

I will convert this as discussion since there is no repro step provide
