### ISSUE TITLE
网站用的是recaptcha，导致iOS客户端无法登陆

### ISSUE THREAD

**Issue by huang545** [cloudreve/ios-feedback#3]
你好，客户端默认似乎只有图形验证码，但是网页端打开recaptcha后是无法登陆的，希望能加入到下一步计划中。

**Comment by vvisionnn** [comment]
Hi @huang545 

just like the test detail we post in the Cloudreve forum, currently we only support the very normal login method, which is email with captcha that Cloudreve backend implemented, using `recaptcha` will be supported in the future, thanks for you feedback.

**Comment by vvisionnn** [comment]
added in release version 1.0
