### ISSUE TITLE
相册备份功能不够完善

### ISSUE THREAD

**Issue by Samler-Lee** [cloudreve/ios-feedback#31]
1、首次备份的情况下，似乎只会备份一次获取到的照片，必须来回切换后台或者重启app才会备份下一批；
2、照片备份没有显示在传输进度列表里。

**Comment by vvisionnn** [comment]
两个都是 by design
1. 相册备份主要是后台备份，主要备份任务在后台（唯一的限制是 iOS，重启机器之后需要打开一次），可以隔一段时间看一下上传数量，正常情况会后台分批备份
2. 相册备份和原本的上传下载处理方式不同，放在一起有歧义


> Both are by design 
> 1. The main photo album backup runs in the background, with most of the backup tasks happening there (the only exception is iOS, which needs to be opened once after a restart). You can check the number of uploads periodically; typically, it will back up in batches in the background.
> 2. The photo album backup operates differently from the original upload and download processes, so combining them could cause confusion.
