### ISSUE TITLE
20220517-反馈

### ISSUE THREAD

**Issue by kindyear** [cloudreve/ios-feedback#6]
## 反馈
首先非常感谢iOS客户端的开发团队，也很荣幸成为第一批的测试Cloudreve iOS客户端的测试员。在这里我会将我个人在使用过程中遇到的一些问题和建议贴在这里，也希望一些好的feature也会加入到正式版软件当中。

### Bug & 问题
1. 在iPhone 13 Pro Max上，底部三个模块的来回切换动画并不是120FPS，目测只有60Fps
2. 

### 建议
1. 在iOS系统程序“文件”中支持直接访问
2. i18n
3. 多站点切换
4. 音频媒体类预览播放
5. iPad OS支援
6. 支持简易的Markdown文本编辑及预览
7. 多种类文件扩展名图标预览

**Comment by vvisionnn** [comment]
Hi @kindyear 

the animation frame rate is important for user experience, thanks for your feedback!

**Comment by vvisionnn** [comment]
Pro Motion frame rate on iPhone 13 Pro/Pro Max have already been fixed, you can upgrade to v1.1.0

iPhone 13 Pro / Pro Max 刷新率问题在 v1.1.0 已修复
